# These are supported funding model platforms
# Sponsorship and Support

- **GitHub**: [PoudyalKumar](https://github.com/PoudyalKumar)
- **Patreon**: [PoudyalKumar](https://www.patreon.com/PoudyalKumar)
- **Open Collective**: [Replace with a single Open Collective username]
- **Ko-fi**: [Replace with a single Ko-fi username]
- **Tidelift**: [Replace with a single Tidelift platform-name/package-name e.g., npm/babel]
- **Community Bridge**: [Replace with a single Community Bridge project-name e.g., cloud-foundry]
- **Liberapay**: [Replace with a single Liberapay username]
- **IssueHunt**: [Replace with a single IssueHunt username]
- **LFX Crowdfunding**: [Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry]
- **Polar**: [Replace with a single Polar username]
- **Buy Me a Coffee**: [Replace with a single Buy Me a Coffee username]
- **Thanks.dev**: [Replace with a single thanks.dev username]
- **Custom**: [Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']]

